default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres

development:
  <<: *default
  database: OrangeTweet_development

test:
  <<: *default
  database: OrangeTweet_test

production:
  <<: *default
  database: OrangeTweet_production
  username: OrangeTweet
  password: <%= ENV['ORANGETWEET_DATABASE_PASSWORD'] %>
